export const GAME_ACTIONS = {
  SET_PLAYER_NAME: "SET_PLAYER_NAME",
  SET_BUSINESS_NAME: "SET_BUSINESS_NAME",
  START_DAY: "START_DAY",
  END_DAY: "END_DAY",
  UNLOCK_UPGRADE: "UNLOCK_UPGRADE",
};

export const AGENT_ACTIONS = {
  ASSIGN_TICKET: "ASSIGN_TICKET",
  REQUEST_HELP: "REQUEST_HELP",
  COMPLETE_TICKET: "COMPLETE_TICKET",
};

export const INBOX_ACTIONS = {
  ADD_MESSAGE: "ADD_MESSAGE",
  MARK_READ: "MARK_READ",
  DELETE_MESSAGE: "DELETE_MESSAGE",
};
