export const GAME_ACTIONS = {
  START_GAME: "START_GAME",
  SET_LOADING: "SET_LOADING",
  RESTART_GAME: "RESTART_GAME",
  ADD_ACTIVITY_LOG: "ADD_ACTIVITY_LOG",
  START_NEW_DAY: "START_NEW_DAY",
  CONTRACT_COMPLETE: "CONTRACT_COMPLETE",
  START_NEW_CONTRACT: "START_NEW_CONTRACT",
  GAME_TICK: "GAME_TICK",
  PAUSE_TIME: "PAUSE_TIME",
  RESUME_TIME: "RESUME_TIME",
  SET_TIME_SPEED: "SET_TIME_SPEED",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
};

export const AGENT_ACTIONS = {
  SET_AGENT_COMMENT: "SET_AGENT_COMMENT",
  SET_AGENT_ACTION: "SET_AGENT_ACTION",
  CREATE_SCREAM: "CREATE_SCREAM",
  WORKING: "WORKING",
  ON_BREAK: "ON_BREAK",
  IDLE: "IDLE",
};

export const INBOX_ACTIONS = {
  ASSIGN_TICKET: "ASSIGN_TICKET",
  ADD_INBOX_ITEM: "ADD_INBOX_ITEM",
  DELETE_SPAM: "DELETE_SPAM",
};

export const SCREAM_ACTIONS = {
  ADD_SCREAM: "ADD_SCREAM",
};

export const LOG_TYPES = {
  ASSIGN_TICKET: "ASSIGN_TICKET",
  AGENT_COMMENT: "AGENT_COMMENT",
  RESOLVE_SUCCESS: "RESOLVE_SUCCESS",
  RESOLVE_FAIL: "RESOLVE_FAIL",
  COMPLAINT_CREATED: "COMPLAINT_CREATED",
  END_DAY: "END_DAY",
  START_DAY: "START_DAY",
  ADD_INBOX_ITEM: "ADD_INBOX_ITEM",
  SCREAM_CREATED: "SCREAM_CREATED",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  INBOX_ITEM_ADDED: "INBOX_ITEM_ADDED",
  // etc
  //Grumble (think cities skylines chirps)
};
