export const GAME_ACTIONS = {
  SET_PLAYER_NAME: "SET_PLAYER_NAME",
  SET_BUSINESS_NAME: "SET_BUSINESS_NAME",
  START_NEW_DAY: "START_NEW_DAY",
  START_GAME: "START_GAME",
  END_DAY: "END_DAY",
  UNLOCK_UPGRADE: "UNLOCK_UPGRADE",
  USE_ACTION_POINT: "USE_ACTION_POINT",
};

export const AGENT_ACTIONS = {
  ASSIGN_TICKET: "ASSIGN_TICKET",
  REQUEST_HELP: "REQUEST_HELP",
  COMPLETE_TICKET: "COMPLETE_TICKET",
  SET_AGENT_COMMENT: "SET_AGENT_COMMENT",
};

export const INBOX_ACTIONS = {
  ADD_MESSAGE: "ADD_MESSAGE",
  MARK_READ: "MARK_READ",
  DELETE_MESSAGE: "DELETE_MESSAGE",
};
