export const GAME_ACTIONS = {
  SET_PLAYER_NAME: "SET_PLAYER_NAME",
  SET_BUSINESS_NAME: "SET_BUSINESS_NAME",
  START_NEW_DAY: "START_NEW_DAY",
  START_GAME: "START_GAME",
  END_DAY: "END_DAY",
  UNLOCK_UPGRADE: "UNLOCK_UPGRADE",
  USE_ACTION_POINT: "USE_ACTION_POINT",
  ADD_ACTIVITY_LOG: "ADD_ACTIVITY_LOG",
};

export const AGENT_ACTIONS = {
  REQUEST_HELP: "REQUEST_HELP",
  COMPLETE_TICKET: "COMPLETE_TICKET",
  SET_AGENT_COMMENT: "SET_AGENT_COMMENT",
  SET_AGENT_ACTION: "SET_AGENT_ACTION",
};

export const INBOX_ACTIONS = {
  ASSIGN_TICKET: "ASSIGN_TICKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  MARK_READ: "MARK_READ",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  RESOLVE_TICKET: "RESOLVE_TICKET",
  UPDATE_TICKET_PROGRESS: "UPDATE_TICKET_PROGRESS",
};

export const LOG_TYPES = {
  ASSIGN_TICKET: "ASSIGN_TICKET",
  AGENT_COMMENT: "AGENT_COMMENT",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  // etc
};
