export const PRE_GENERATED_AGENTS = [
  {
    agentName: "Terry Blazer",
    nickName: "Blaze",
    age: 54,
    gender: "male",
    personality: {
      traits: ["sassy", "paranoid", "chaotic"],
      favFood: "protein bars",
    },
    skills: {
      hardware: 0,
      software: 3,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Ronnie Stokes",
    nickName: "Stokey",
    age: 25,
    gender: "male",
    personality: {
      traits: ["laid-back", "sassy", "awkward"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 2,
      software: 10,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Max Kline",
    nickName: "Maxx",
    age: 34,
    gender: "male",
    personality: {
      traits: ["goofy", "stoic", "sassy"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 7,
      software: 1,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Eduardo Vega",
    nickName: "Edge",
    age: 32,
    gender: "male",
    personality: {
      traits: ["laid-back", "goofy", "paranoid"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 4,
      software: 9,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Jin Park",
    nickName: "Jinny",
    age: 32,
    gender: "male",
    personality: {
      traits: ["sassy", "paranoid", "friendly"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 7,
      software: 8,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Lars Morgan",
    nickName: "L-Mo",
    age: 27,
    gender: "male",
    personality: {
      traits: ["laid-back", "sassy", "overconfident"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 7,
      software: 2,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Omar Patel",
    nickName: "O.P.",
    age: 43,
    gender: "male",
    personality: {
      traits: ["charismatic", "meticulous", "laid-back"],
      favFood: "instant noodles",
    },
    skills: {
      hardware: 2,
      software: 0,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Ricky Blaze",
    nickName: "RickRoll",
    age: 55,
    gender: "male",
    personality: {
      traits: ["grumpy", "awkward", "charismatic"],
      favFood: "cold pizza",
    },
    skills: {
      hardware: 3,
      software: 3,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Fred Chu",
    nickName: "Chubbs",
    age: 37,
    gender: "male",
    personality: {
      traits: ["stoic", "robotic", "serious"],
      favFood: "protein bars",
    },
    skills: {
      hardware: 3,
      software: 9,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Malcolm Voss",
    nickName: "Voss",
    age: 39,
    gender: "male",
    personality: {
      traits: ["goofy", "awkward", "overconfident"],
      favFood: "cold pizza",
    },
    skills: {
      hardware: 3,
      software: 0,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Lena Sharp",
    nickName: "Shiv",
    age: 41,
    gender: "female",
    personality: {
      traits: ["stoic", "goofy", "awkward"],
      favFood: "instant noodles",
    },
    skills: {
      hardware: 5,
      software: 1,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Zara Wu",
    nickName: "Zee",
    age: 31,
    gender: "female",
    personality: {
      traits: ["paranoid", "grumpy", "goofy"],
      favFood: "spicy burritos",
    },
    skills: {
      hardware: 10,
      software: 4,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Nina Bell",
    nickName: "Bells",
    age: 23,
    gender: "female",
    personality: {
      traits: ["robotic", "serious", "burnt-out"],
      favFood: "protein bars",
    },
    skills: {
      hardware: 4,
      software: 3,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Jules Moreno",
    nickName: "Mo",
    age: 55,
    gender: "female",
    personality: {
      traits: ["robotic", "burnt-out", "grumpy"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 0,
      software: 6,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Aiko Tanaka",
    nickName: "AI-Ko",
    age: 54,
    gender: "female",
    personality: {
      traits: ["overconfident", "laid-back", "awkward"],
      favFood: "instant noodles",
    },
    skills: {
      hardware: 0,
      software: 5,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Frances Ray",
    nickName: "RayRay",
    age: 49,
    gender: "female",
    personality: {
      traits: ["sassy", "goofy", "awkward"],
      favFood: "cheese toasties",
    },
    skills: {
      hardware: 10,
      software: 8,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Mira Doyle",
    nickName: "DoyleRules",
    age: 39,
    gender: "female",
    personality: {
      traits: ["serious", "awkward", "friendly"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 7,
      software: 5,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Casey Singh",
    nickName: "SinghSong",
    age: 51,
    gender: "female",
    personality: {
      traits: ["stoic", "serious", "laid-back"],
      favFood: "energy drinks",
    },
    skills: {
      hardware: 6,
      software: 4,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Bea Armstrong",
    nickName: "BeaByte",
    age: 43,
    gender: "female",
    personality: {
      traits: ["stoic", "paranoid", "meticulous"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 5,
      software: 7,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Sylvia Knox",
    nickName: "Syl",
    age: 41,
    gender: "female",
    personality: {
      traits: ["stoic", "charismatic", "goofy"],
      favFood: "energy drinks",
    },
    skills: {
      hardware: 3,
      software: 9,
    },
    currentAction: "idle",
    currentEmotion: "annoyed",
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
];
