export const PRE_GENERATED_AGENTS = [
  {
    agentName: "Terry Blazer",
    nickName: "Blaze",
    age: 54,
    gender: "male",
    personality: {
      traits: ["sassy", "paranoid", "chaotic"],
      quirks: [
        "types with one finger",
        "quotes sci-fi movies during calls",
        "insists on using their own custom keyboard",
      ],
      likes: ["dark mode", "coffee", "mechanical keyboards"],
      dislikes: ["mouse acceleration", "management buzzwords", "Zoom calls"],
      favFood: "protein bars",
    },
    skills: {
      hardware: 0,
      software: 3,
      people: 2,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    moodScore: -9,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Ronnie Stokes",
    nickName: "Stokey",
    age: 25,
    gender: "male",
    personality: {
      traits: ["laid-back", "sassy", "awkward"],
      quirks: [
        "types with one finger",
        "restarts everything twice for good luck",
        "insists on using their own custom keyboard",
      ],
      likes: ["office gossip", "mechanical keyboards", "user rage"],
      dislikes: ["paperwork", "outlook crashes", "printers"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 2,
      software: 10,
      people: 10,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: -7,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Max Kline",
    nickName: "Maxx",
    age: 34,
    gender: "male",
    personality: {
      traits: ["goofy", "stoic", "sassy"],
      quirks: [
        "records their own hold music",
        "rants about cable management",
        "quotes sci-fi movies during calls",
      ],
      likes: ["chaos", "user rage", "dark mode"],
      dislikes: ["Zoom calls", "VPNs", "printers"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 7,
      software: 1,
      people: 7,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: -4,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Eduardo Vega",
    nickName: "Edge",
    age: 32,
    gender: "male",
    personality: {
      traits: ["laid-back", "goofy", "paranoid"],
      quirks: [
        "talks to their computer like it\u2019s a person",
        "rants about cable management",
        "restarts everything twice for good luck",
      ],
      likes: ["clean cable runs", "ASCII art", "mechanical keyboards"],
      dislikes: ["Zoom calls", "management buzzwords", "outlook crashes"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 4,
      software: 9,
      people: 10,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    moodScore: -8,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Jin Park",
    nickName: "Jinny",
    age: 32,
    gender: "male",
    personality: {
      traits: ["sassy", "paranoid", "friendly"],
      quirks: [
        "records their own hold music",
        "insists on using their own custom keyboard",
        "types with one finger",
      ],
      likes: ["coffee", "chaos", "flow charts"],
      dislikes: ["Zoom calls", "typos", "outlook crashes"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 7,
      software: 8,
      people: 5,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    moodScore: 4,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Lars Morgan",
    nickName: "L-Mo",
    age: 27,
    gender: "male",
    personality: {
      traits: ["laid-back", "sassy", "overconfident"],
      quirks: [
        "keeps a cactus named Kevin on their desk",
        "only works to synthwave music",
        "types with one finger",
      ],
      likes: ["flow charts", "clean cable runs", "office gossip"],
      dislikes: ["management buzzwords", "outlook crashes", "typos"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 7,
      software: 2,
      people: 2,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: -1,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Omar Patel",
    nickName: "O.P.",
    age: 43,
    gender: "male",
    personality: {
      traits: ["charismatic", "meticulous", "laid-back"],
      quirks: [
        "quotes sci-fi movies during calls",
        "restarts everything twice for good luck",
        "keeps a cactus named Kevin on their desk",
      ],
      likes: ["dark mode", "clean cable runs", "coffee"],
      dislikes: ["paperwork", "management buzzwords", "outlook crashes"],
      favFood: "instant noodles",
    },
    skills: {
      hardware: 2,
      software: 0,
      people: 5,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    moodScore: -3,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Ricky Blaze",
    nickName: "RickRoll",
    age: 55,
    gender: "male",
    personality: {
      traits: ["grumpy", "awkward", "charismatic"],
      quirks: [
        "talks to their computer like it\u2019s a person",
        "quotes sci-fi movies during calls",
        "keeps a cactus named Kevin on their desk",
      ],
      likes: ["chaos", "office gossip", "flow charts"],
      dislikes: ["Zoom calls", "paperwork", "VPNs"],
      favFood: "cold pizza",
    },
    skills: {
      hardware: 3,
      software: 3,
      people: 7,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    moodScore: -3,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Fred Chu",
    nickName: "Chubbs",
    age: 37,
    gender: "male",
    personality: {
      traits: ["stoic", "robotic", "serious"],
      quirks: [
        "types with one finger",
        "talks to their computer like it\u2019s a person",
        "keeps a cactus named Kevin on their desk",
      ],
      likes: ["user rage", "coffee", "dark mode"],
      dislikes: ["printers", "paperwork", "VPNs"],
      favFood: "protein bars",
    },
    skills: {
      hardware: 3,
      software: 9,
      people: 7,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    moodScore: 6,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Malcolm Voss",
    nickName: "Voss",
    age: 39,
    gender: "male",
    personality: {
      traits: ["goofy", "awkward", "overconfident"],
      quirks: [
        "types with one finger",
        "records their own hold music",
        "restarts everything twice for good luck",
      ],
      likes: ["clean cable runs", "coffee", "office gossip"],
      dislikes: ["printers", "typos", "paperwork"],
      favFood: "cold pizza",
    },
    skills: {
      hardware: 3,
      software: 0,
      people: -1,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    moodScore: 3,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Lena Sharp",
    nickName: "Shiv",
    age: 41,
    gender: "female",
    personality: {
      traits: ["stoic", "goofy", "awkward"],
      quirks: [
        "quotes sci-fi movies during calls",
        "insists on using their own custom keyboard",
        "keeps a cactus named Kevin on their desk",
      ],
      likes: ["chaos", "coffee", "vaporwave"],
      dislikes: ["management buzzwords", "mouse acceleration", "printers"],
      favFood: "instant noodles",
    },
    skills: {
      hardware: 5,
      software: 1,
      people: 8,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: 1,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Zara Wu",
    nickName: "Zee",
    age: 31,
    gender: "female",
    personality: {
      traits: ["paranoid", "grumpy", "goofy"],
      quirks: [
        "types with one finger",
        "restarts everything twice for good luck",
        "rants about cable management",
      ],
      likes: ["ASCII art", "clean cable runs", "dark mode"],
      dislikes: ["VPNs", "outlook crashes", "management buzzwords"],
      favFood: "spicy burritos",
    },
    skills: {
      hardware: 10,
      software: 4,
      people: 6,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    moodScore: 1,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Nina Bell",
    nickName: "Bells",
    age: 23,
    gender: "female",
    personality: {
      traits: ["robotic", "serious", "burnt-out"],
      quirks: [
        "talks to their computer like it\u2019s a person",
        "insists on using their own custom keyboard",
        "keeps a cactus named Kevin on their desk",
      ],
      likes: ["mechanical keyboards", "dark mode", "clean cable runs"],
      dislikes: ["printers", "outlook crashes", "Zoom calls"],
      favFood: "protein bars",
    },
    skills: {
      hardware: 4,
      software: 3,
      people: 1,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: 10,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Jules Moreno",
    nickName: "Mo",
    age: 55,
    gender: "female",
    personality: {
      traits: ["robotic", "burnt-out", "grumpy"],
      quirks: [
        "keeps a cactus named Kevin on their desk",
        "quotes sci-fi movies during calls",
        "talks to their computer like it\u2019s a person",
      ],
      likes: ["coffee", "mechanical keyboards", "office gossip"],
      dislikes: ["outlook crashes", "printers", "management buzzwords"],
      favFood: "bubble tea",
    },
    skills: {
      hardware: 0,
      software: 6,
      people: 5,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    moodScore: 8,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Aiko Tanaka",
    nickName: "AI-Ko",
    age: 54,
    gender: "female",
    personality: {
      traits: ["overconfident", "laid-back", "awkward"],
      quirks: [
        "talks to their computer like it\u2019s a person",
        "records their own hold music",
        "rants about cable management",
      ],
      likes: ["user rage", "vaporwave", "chaos"],
      dislikes: ["printers", "Zoom calls", "typos"],
      favFood: "instant noodles",
    },
    skills: {
      hardware: 0,
      software: 5,
      people: 6,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    moodScore: 10,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Frances Ray",
    nickName: "RayRay",
    age: 49,
    gender: "female",
    personality: {
      traits: ["sassy", "goofy", "awkward"],
      quirks: [
        "writes poetry in error messages",
        "rants about cable management",
        "only works to synthwave music",
      ],
      likes: ["clean cable runs", "user rage", "chaos"],
      dislikes: ["paperwork", "management buzzwords", "outlook crashes"],
      favFood: "cheese toasties",
    },
    skills: {
      hardware: 10,
      software: 8,
      people: 9,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: 2,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Mira Doyle",
    nickName: "DoyleRules",
    age: 39,
    gender: "female",
    personality: {
      traits: ["serious", "awkward", "friendly"],
      quirks: [
        "keeps a cactus named Kevin on their desk",
        "rants about cable management",
        "quotes sci-fi movies during calls",
      ],
      likes: ["mechanical keyboards", "flow charts", "dark mode"],
      dislikes: ["typos", "Zoom calls", "mouse acceleration"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 7,
      software: 5,
      people: 0,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    moodScore: 5,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Casey Singh",
    nickName: "SinghSong",
    age: 51,
    gender: "female",
    personality: {
      traits: ["stoic", "serious", "laid-back"],
      quirks: [
        "keeps a cactus named Kevin on their desk",
        "writes poetry in error messages",
        "insists on using their own custom keyboard",
      ],
      likes: ["dark mode", "chaos", "vaporwave"],
      dislikes: ["management buzzwords", "printers", "outlook crashes"],
      favFood: "energy drinks",
    },
    skills: {
      hardware: 6,
      software: 4,
      people: 5,
    },
    currentAction: "idle",
    currentEmotion: "excited",
    moodScore: -10,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Bea Armstrong",
    nickName: "BeaByte",
    age: 43,
    gender: "female",
    personality: {
      traits: ["stoic", "paranoid", "meticulous"],
      quirks: [
        "keeps a cactus named Kevin on their desk",
        "only works to synthwave music",
        "rants about cable management",
      ],
      likes: ["mechanical keyboards", "dark mode", "ASCII art"],
      dislikes: ["mouse acceleration", "printers", "outlook crashes"],
      favFood: "double-shot espresso",
    },
    skills: {
      hardware: 5,
      software: 7,
      people: 3,
    },
    currentAction: "idle",
    currentEmotion: "focused",
    moodScore: 9,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
  {
    agentName: "Sylvia Knox",
    nickName: "Syl",
    age: 41,
    gender: "female",
    personality: {
      traits: ["stoic", "charismatic", "goofy"],
      quirks: [
        "records their own hold music",
        "keeps a cactus named Kevin on their desk",
        "quotes sci-fi movies during calls",
      ],
      likes: ["chaos", "mechanical keyboards", "clean cable runs"],
      dislikes: ["outlook crashes", "VPNs", "mouse acceleration"],
      favFood: "energy drinks",
    },
    skills: {
      hardware: 3,
      software: 9,
      people: 4,
    },
    currentAction: "idle",
    currentEmotion: "annoyed",
    moodScore: 9,
    memoryLog: [],
    personalStatement: "I just want the tech to work, is that too much to ask?",
    currentComment: null,
  },
];
