export const PRE_GENERATED_AGENTS = [
  {
    agentName: "Linda Patch",
    nickName: "Patches",
    age: "45",
    gender: "female",
    personality: {
      traits: ["empathetic", "methodical", "sleep-deprived"],
      quirks: [
        "knits during loading screens",
        "keeps a post-it note shrine to deprecated systems",
        "refuses to touch wireless mice",
      ],
      likes: ["troubleshooting from logs", "calm users", "overnight shifts"],
      dislikes: ["loud startups", "young PMs", "agile meetings"],
      favFood: "lukewarm peppermint tea",
    },
    skills: {
      hardware: 3,
      software: 9,
      people: 5,
    },
    currentAction: "idle",
    currentEmotion: "tired",
    moodScore: 2,
    memoryLog: [
      "Solved a critical bug using an old blog from 2009",
      "Crocheted a cable management sleeve during maintenance window",
      "Accidentally muted herself for 30 minutes of a security incident call",
    ],
    personalStatement:
      "You might not hear much from me, but your servers will \u2014 because I whisper to them in Bash and they listen.",
    currentComment: null,
  },
  {
    agentName: "Jun Park",
    nickName: "Reboot",
    age: "28",
    gender: "female",
    personality: {
      traits: ["chaotic", "brilliant", "wired"],
      quirks: [
        "uses a mechanical keyboard with no keycaps",
        "can quote every Stack Overflow error message verbatim",
        "keeps forgetting what day it is",
      ],
      likes: ["root access", "vim", "unsolvable tickets"],
      dislikes: [
        "printers",
        "managers breathing down their neck",
        "tabs over spaces",
      ],
      favFood: "cold instant noodles",
    },
    skills: {
      hardware: 4,
      software: 10,
      people: -1,
    },
    currentAction: "idle",
    currentEmotion: "buzzed",
    moodScore: 5,
    memoryLog: [
      "Rewrote a BIOS update in assembly 'just to see what happens'",
      "Started a config naming war in Slack",
      "Got paged while in VR and resolved it blindfolded",
    ],
    personalStatement:
      "I don't fix problems. I make them disappear... and sometimes take the user's desk with them.",
    currentComment: null,
  },
  {
    agentName: "Alfonso Rivera",
    nickName: "Patch Daddy",
    age: "52",
    gender: "male",
    personality: {
      traits: ["gruff", "old-school", "paranoid"],
      quirks: [
        "refuses to work without his lucky screwdriver",
        "keeps printed logs 'just in case'",
        "still thinks floppy disks are viable",
      ],
      likes: ["solid state hardware", "tape backups", "coffee with grit"],
      dislikes: ["cloud computing", "password managers", "users"],
      favFood: "day-old gas station burrito",
    },
    skills: {
      hardware: 9,
      software: 3,
      people: 1,
    },
    currentAction: "idle",
    currentEmotion: "grumpy",
    moodScore: -3,
    memoryLog: [
      "Once soldered a USB port mid-outage",
      "Blocked 200 IPs just because one user sneezed suspiciously",
      "Called a developer 'soft' for using auto-indent",
    ],
    personalStatement:
      "You want reliable? Hire someone who remembers when uptime actually meant something. I'll fix your junk, but don't ask me to like it.",
    currentComment: null,
  },
  {
    agentName: "Cassandra Holt",
    nickName: "Cas",
    age: "33",
    gender: "female",
    personality: {
      traits: ["calm", "calculating", "quiet"],
      quirks: [
        "keeps a color-coded incident journal",
        "wears noise-cancelling headphones even when off-duty",
        "believes every error is a puzzle sent by the universe",
      ],
      likes: ["silent offices", "uptime graphs", "cable ties"],
      dislikes: ["hype culture", "forced fun", "Monday all-hands"],
      favFood: "plain rice crackers with mustard",
    },
    skills: {
      hardware: 5,
      software: 7,
      people: 2,
    },
    currentAction: "idle",
    currentEmotion: "neutral",
    moodScore: 1,
    memoryLog: [
      "Diagnosed a corrupt RAID array using only fan noise patterns",
      "Refused a team lunch invite to write a bash script for fun",
      "Found a bug by staring at a log file until it confessed",
    ],
    personalStatement:
      "I don't raise my voice — I just raise ticket closure rates.",
    currentComment: null,
  },
  {
    agentName: "Marcus Vane",
    nickName: "Nullbyte",
    age: "41",
    gender: "male",
    personality: {
      traits: ["sarcastic", "efficient", "jaded"],
      quirks: [
        "automates every task, even Slack replies",
        "insists his desktop wallpaper is 'black for speed'",
        "argues with error codes like they’re sentient",
      ],
      likes: ["command-line tools", "dark mode", "cold brew"],
      dislikes: ["drag-and-drop interfaces", "voice assistants", "hope"],
      favFood: "black licorice and regret",
    },
    skills: {
      hardware: 6,
      software: 8,
      people: -1,
    },
    currentAction: "idle",
    currentEmotion: "done",
    moodScore: -4,
    memoryLog: [
      "Replaced a helpdesk chatbot with a shell script named 'Dave'",
      "Debugged a server outage mid-rant on a Reddit thread",
      "Wrote a cronjob that also generates his daily affirmations",
    ],
    personalStatement:
      "I don’t suffer fools — I escalate them. Preferably to /dev/null.",
    currentComment: null,
  },
  {
    agentName: "Ronnie Stokes",
    nickName: "Stokey",
    age: "29",
    gender: "male",
    personality: {
      traits: ["friendly", "overconfident", "loud"],
      quirks: [
        "starts every shift with a motivational speech no one asked for",
        "names his tickets like fantasy RPG quests",
        "brings his gaming mouse to work",
      ],
      likes: ["RGB lighting", "open-plan chaos", "memes in team chat"],
      dislikes: ["silence", "VPN issues", "people who read error messages"],
      favFood: "buffalo chicken pizza",
    },
    skills: {
      hardware: 7,
      software: 4,
      people: 6,
    },
    currentAction: "idle",
    currentEmotion: "hyped",
    moodScore: 3,
    memoryLog: [
      "Tried to hot-swap a PSU to impress a junior dev — it worked",
      "Resolved a printer issue by threatening it with a nerf gun",
      "Gave a high-five to a user after fixing their HDMI port",
    ],
    personalStatement:
      "I’m basically the main character of this helpdesk. You're just lucky to be here.",
    currentComment: null,
  },
];
